<?php
/**
 * @var \Conekta\Payments\Block\Bnpl\BnplInfo $block
 */
?>
<p>
    <strong><?= $block->escapeHtml(__('Payment Method:')) ?></strong>
    <?= $block->escapeHtml(__('Buy Now Pay Later (BNPL)')) ?>
</p>

<?php if ($block->getSpecificInformation()): ?>
    <table class="data-table admin__table-secondary">
        <tbody>
            <?php foreach ($block->getSpecificInformation() as $label => $value): ?>
                <tr>
                    <td><?= $block->escapeHtml($label) ?>:</td>
                    <td><?= $block->escapeHtml($value) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php if ($block->getChildHtml()): ?>
    <div class="nested">
        <?= $block->getChildHtml() ?>
    </div>
<?php endif; ?>
