<?php
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <dt class="title"><?php /* @noEscape */ echo $title; ?></dt>
    <dd style="margin: 0 !important; -webkit-margin-start: 0 !important;">
        <table class="data-table admin__table-secondary">
            <tbody>
                <tr>
                    <th><strong><?php echo __('Credit Card Type:'); ?></strong></th>
                    <td>
                        <?php echo $block->getCcTypeName(); ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </dd>
</dl>
<?php echo $block->getChildHtml(); ?>
