<?php
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <dt class="title"><?= /* @noEscape */ $title; ?></dt>
    <dd style="margin: 0 !important; -webkit-margin-start: 0 !important;">
        <table class="data-table admin__table-secondary">
            <tbody>
                <tr>
                    <th><strong><?= /* @noEscape */ __('Credit Card Type:'); ?></strong></th>
                    <td>
                        <?= $block->escapeHtml($block->getCcTypeName()); ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </dd>
</dl>
<?= $block->getChildHtml(); ?>
